In [14]:
import pandas as pd

In [3]:
df = pd.read_excel("./data.xlsx")

In [1]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [9]:
categories = ['green', 'blue', 'red', 'red', 'blue']
categories_array = np.array(categories).reshape(-1, 1)

In [10]:
encoder = OneHotEncoder()

In [11]:
one_hot_encoded = encoder.fit_transform(categories_array)

In [12]:
# Convert the sparse matrix to a dense array
one_hot_encoded_array = one_hot_encoded.toarray()

In [13]:
one_hot_encoded_array

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [15]:
df = pd.read_csv("./data/Housing.csv")

In [16]:
df.head()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   
2  12250000  9960         3          2        2      yes        no      yes   
3  12215000  7500         4          2        2      yes        no      yes   
4  11410000  7420         4          1        2      yes       yes      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished  
3              no             yes        3      yes        furnished  
4              no             yes        2       no        furnished

In [17]:
encoder = OneHotEncoder()

In [18]:
furnished_status = df['furnishingstatus']


In [31]:
furnished_status.unique()

array(['furnished', 'semi-furnished', 'unfurnished'], dtype=object)

In [32]:
categories_array = np.array(furnished_status).reshape(-1, 1)

In [33]:
one_hot_encoded = encoder.fit_transform(categories_array)

In [34]:
one_hot_encoded_array = one_hot_encoded.toarray()

In [36]:
print(one_hot_encoded_array)

[[1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 ...
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [39]:
new_df = pd.DataFrame(one_hot_encoded_array,furnished_status)

In [40]:
new_df

0    1    2
furnishingstatus               
furnished         1.0  0.0  0.0
furnished         1.0  0.0  0.0
semi-furnished    0.0  1.0  0.0
furnished         1.0  0.0  0.0
furnished         1.0  0.0  0.0
...               ...  ...  ...
unfurnished       0.0  0.0  1.0
semi-furnished    0.0  1.0  0.0
unfurnished       0.0  0.0  1.0
furnished         1.0  0.0  0.0
unfurnished       0.0  0.0  1.0

[545 rows x 3 columns]