# Lab 4. Probabilistic Inference
# Task 4.2 Diabetes Diagnosis Using Naïve Bayes 
## Problem Descriptions
Assume that we have various
of observations from patients such as basic personal details (age, gender, height,
weight etc), body test data (blood sugar, heart rate, lipoproteins etc) and symptoms
(fever, headache etc), we will try to predict if the patient is suffered from a certain
disease or the progression level of the disease.
We will use the diabetes dataset provided in sklearn, which contains 10 features and
one quantitative measure of diabetes progression.(course material)

## Implementation and Results

In [ ]:
!pip install sklearn
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split, cross_validate

# import numpy as np
import matplotlib.pyplot as plt
# from matplotlib import patches
import math

In [ ]:
diabetes = datasets.load_diabetes()
# X = diabetes.data[:,[2,3,9]]
X = diabetes.data
Y = [math.floor(x/150) for x in diabetes.target]

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25)

nb = GaussianNB()
nb.fit(X_train, Y_train)
Y_pred = nb.predict(X_test)
acc = accuracy_score(Y_test, Y_pred)
cm = confusion_matrix(Y_test, Y_pred)
cr = classification_report(Y_test, Y_pred)

print("Accuracy:", acc)
print("Confusion Matrix:\n", cm)
print("Prior:\n", nb.class_prior_)
print("Mean:\n", nb.theta_)
print("Variance:\n", nb.sigma_)


Accuracy: 0.5765765765765766
Confusion Matrix:
 [[44 20  0]
 [21 20  4]
 [ 1  1  0]]
Prior:
 [0.52567976 0.43806647 0.03625378]
Mean:
 [[-0.00566069 -0.00026772 -0.02115285 -0.01479883 -0.00689089 -0.00573395
   0.01785399 -0.01777262 -0.02305142 -0.01417056]
 [ 0.00813878  0.00071837  0.02121507  0.0166012   0.01194385  0.00990548
  -0.01826415  0.01971383  0.0269613   0.01554786]
 [ 0.01476712  0.0189062   0.08648588  0.03765218  0.00198559 -0.00136607
  -0.03971921  0.04045905  0.04584685  0.04655653]]
Variance:
 [[0.00225479 0.00226076 0.00141088 0.00176366 0.00226593 0.00226513
  0.0025671  0.00167838 0.00150926 0.00196946]
 [0.00218156 0.00226627 0.00190433 0.00216413 0.00211941 0.00207609
  0.00119865 0.00185704 0.00184259 0.00231561]
 [0.00176259 0.00201916 0.00169741 0.00245455 0.00156965 0.00122023
  0.00052411 0.00200471 0.00119533 0.00144262]]
[ 0.03807591  0.05068012  0.06169621  0.02187235 -0.0442235  -0.03482076
 -0.04340085 -0.00259226  0.01990842 -0.01764613] 151.0
[-0

## Discussions

the accuracy of our model is 0.57.
we used naive bayes in above programme. 
definition of the naive bayes from wikepedia is as follows:--

* Naive Bayes classifiers are highly scalable, requiring a number of parameters linear in the number of variables (features/predictors) in a learning problem. Maximum-likelihood training can be done by evaluating a closed-form expression, which takes linear time, rather than by expensive iterative approximation as used for many other types of classifiers.


to our trained model we pass the inputs which is factors influencing diabities and as a ouput we het the probability of person being diabatic.